spring.application.name=DesafioForoAlura

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/forohub_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Para desarrollo: flexible
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JWT
jwt.secret=clave_secreta_super_segura_para_desarrollo_12345678901234567890
jwt.expiration=3600000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html